### PR TITLE
Update extension to work with Solidus 4.4

### PR DESCRIPTION
**Pull request by boomer196**
## What does this PR do?
* Update `.circleci/config.yml` to use ruby `3.2` during testing (required for circleci)
* Update the `Gemfile` to match latest version of `solidus_dev_support`.  (specifying sqlite3' `'~> 1.4'` was required for circleci)
* Update `app/models/spree/stock/splitter/digital_splitter.rb` to use `digitals.each_value` to fix rubocop violation.
* `solidus_digital.gemspec` was depending on `solidus` instead of just `solidus_core`
  * This matches the latest version of `solidus_dev_support` gemspec template
  * This also makes it so application using this gem do not have `legacy_promotions` pulled into their application.
* With `Solidus@4.4.1` an exception was being raised:
```
on_file_autoloaded': expected file solidus_digital/app/overrides/add_digital_downloads_to_invoice.rb to define constant AddDigitalDownloadsToInvoice, but didn't (Zeitwerk::NameError)
```
To fix this an `initializer` was added to ignore the autoloads was added and the file moved into a sub-directory  (For some reason circleci required it to be moved, while the application didn't care)

**NOTE:**  This broken "override" that was moved is not actually used in `solidus_starter_frontend`.  It is a "carry-over" from Spree (`spree_rails_frontend` [application](https://github.com/spree/spree_rails_frontend/blob/3f41643dbebb663840cc7be22b555f8b2abb43c3/app/views/spree/shared/_order_details.html.erb#L80)).  You can also take a look at the deprecated `solidus_frontend` [application](https://github.com/solidusio/solidus_frontend/blob/main/app/views/spree/shared/_order_details.html.erb).  You can use it as an example of how to add links.  See this [disclaimer](https://github.com/solidusio/solidus_starter_frontend/blob/6a0190c8ed1eca5f261e9fb1e5cf0d54345ba61e/README.md?plain=1#L12) for more information.

### CODE REVIEW

**Comment by fthobe** [comment]
Hey @boomer196 I think @kennyadsl would be more than happy to help you on making the tests work and merge it.

**Comment by fthobe** [comment]
Hey @boomer196 there seems to be an auth Problem and a gemfile Problem when circleci runs that is not related to your changes but caused by two previous PRs that shouldn't have been merged. I opened issue #32 to investigate.

**Comment by fthobe** [comment]
@boomer196 you should consider merging all restoration PRs into one clean PR. @jarednorman @tvdeyen this looks like good and clean work to me and this extension needs some love. Maybe one of you three could take a look at this.

**Comment by kennyadsl** [comment]
I think I fixed the auth problem (renewing the SSH key associate with the CircleCI project). Let's see how the build goes now.

**Comment by kennyadsl** [comment]
Auth issue solved, but there seem to be a real failure testing against Solidus 4.4, which seems related to the ruby version used:

```
Fetching https://github.com/solidusio/solidus.git
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Could not find compatible versions

Because every version of solidus depends on Ruby >= 3.1.0
  and Gemfile depends on solidus >= 0,
  Ruby >= 3.1.0 is required.
So, because current Ruby version is = 3.0.7,
  version solving has failed.

Exited with code exit status 6
```

**Comment by fthobe** [comment]
Guys, I can see this going over the finish line!!!!

**Comment by boomer196** [comment]
Thanks @kennyadsl ... let me see if I can get this PR to go green.

**Comment by boomer196** [comment]
@kennyadsl, I have this PR passing circleci.  My other PRs can be stacked on this one.....or once this is merged rebased off of master.....or combined into one PR.  Please let me know your preference.

I think I would prefer merging this one and then rebasing others, but am fine with whatever.   This PR is required to get the gem running in solidus.  The others (1 bugfix and 1 ui treatment) are separate IMO.

**Comment by kennyadsl** [comment]
Agree. It's ok to merge this one and rebase the others against main.

**Review by kennyadsl — APPROVED** [review]
Great work. Thanks for the contribution. 👌👌

**Pull request merged**
